---
deployment:
  tasks:
    # Banner inicial com timestamp
    - echo "==== DEPLOY START $(date -u +%Y-%m-%dT%H:%M:%SZ) ===="

    # Ativa ambiente Node da aplicação (garante versão correta) e define produção
    - . /home/cfauto/nodevenv/rent.cfauto.com.br/backend/20/bin/activate && export NODE_ENV=production && set -e && echo "== Ambiente ==" && pwd && echo "NODE $(node -v)" && which node

    # Backend deps (usa ci para instalação limpa). Flags: --omit=dev sem audit/fund para acelerar
    - . /home/cfauto/nodevenv/rent.cfauto.com.br/backend/20/bin/activate && echo "== (Backend) npm ci start $(date +%H:%M:%S) ==" && npm --prefix backend ci --omit=dev --no-audit --no-fund && echo "== (Backend) npm ci done $(date +%H:%M:%S) =="

    # Frontend build
    - . /home/cfauto/nodevenv/rent.cfauto.com.br/backend/20/bin/activate && echo "== (Frontend) deps+build start $(date +%H:%M:%S) ==" && npm --prefix frontend ci --no-audit --no-fund && npm --prefix frontend run build && echo "== (Frontend) build done $(date +%H:%M:%S) =="

    # Admin build
    - . /home/cfauto/nodevenv/rent.cfauto.com.br/backend/20/bin/activate && echo "== (Admin) deps+build start $(date +%H:%M:%S) ==" && npm --prefix admin ci --no-audit --no-fund && npm --prefix admin run build && echo "== (Admin) build done $(date +%H:%M:%S) =="

    # Limpa bundles antigos para evitar lixo
    - echo "== Limpeza bundles antigos $(date +%H:%M:%S) ==" && rm -rf backend/public/frontend/* backend/public/admin/* || true

    # Garante diretórios e copia novos bundles
    - echo "== Preparando diretórios de destino ==" && mkdir -p backend/public/frontend backend/public/admin
    - echo "== Copiando bundles para backend/public $(date +%H:%M:%S) ==" && rsync -a frontend/dist/ backend/public/frontend/ && rsync -a admin/dist/ backend/public/admin/

    # Lista conteúdo para debug rápido
    - echo "== Conteúdo copiado (index.html encontrados) ==" && find backend/public -maxdepth 2 -type f -name 'index.html'

    # Reinicia Passenger para carregar novo código
    - echo "== Reiniciando Passenger $(date +%H:%M:%S) ==" && mkdir -p backend/tmp && touch backend/tmp/restart.txt

    # Final
    - echo "==== DEPLOY END $(date -u +%Y-%m-%dT%H:%M:%SZ) ===="
